### ISSUE TITLE
VERY minor issue with readme

### ISSUE THREAD

**Issue by TrentWell** [xebialabs-community/xlr-gitlab-plugin#13]
The release page link goes to the wrong plugin. 

Gitlab 'release page' goes to https://github.com/xebialabs-community/xlr-qualys-plugin/releases
not https://github.com/xebialabs-community/xlr-gitlab-plugin/releases

**Comment by ndebuhr** [comment]
Thank you for point this out @TrentWell !   Fixed on master.
